# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AjfmQ5KnBRjNK6QEy3ccOe3FghMsBjS8xjnD6Ez9mh7ifZV1N26CJZUks7vMBK/cyqVika2rZZkc3vLTnWQLS4A0XdiOfutBsuOvTYWKXEMElxreR0LcLxipCMa1HhnwQVeB+78prlQyUt4baj+ZPAsqqhLU2cKddmk4YgKbTjYUDKq1JO22BlLsyJJG+ZoTKFxsanEWSMU9ioy3PTV5JM+XiKVf42fZz4GdHVEr+UcZTz3cvcvsqUg/pLguYyK0pGcU7Iykeat+yLoORF2zXI2pf8Xpy0FNFs27PBNn2r5oW4Ripc0VAJZy2OWxAMg3tHS3LnHqlMtM2pJSDkL11puwvTfNK3XWQG60rztbVIrnVcuRcGvQdIbZOWT941V8vXP2Qn7GHrSYcP5wO87vV2YSwt6Ncx3tzv+5lRrErj1NKUALdtWCmg73CGcbN7r2HRvSEKd8UvVm+KbL/PN/7dzyQ0ifWGbfSrPXqlX3/b0jZfRJ2lO615VNyw2Y/1DYmI2DgN9yt46xca2Wx3vBMNCdeUCwhu5MCNwNZhqIAFT5wvXouZHRpdX9hnk4XJm0ARyXyJ5C3N/SKJ0Ut7QFX+JWI+N3nVCX7w9T8F8NwJ7aBBRYfU9O27gwaTYdT+RlC7TU72jHh+xMcXI0J52UM3S1XiNRJJXZpnpaObvRaeA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
